CREATE DATABASE ImobiliariaBI;

USE ImobiliariaBI;

DROP TABLE FATO_IMOVEL;
DROP TABLE PROPRIETARIO;
DROP TABLE TEMPO;
DROP TABLE CATEGORIA;
DROP TABLE BAIRRO;
DROP TABLE CIDADE;
DROP TABLE ESTADO;

CREATE TABLE ESTADO (
  ID_ESTADO INT NOT NULL AUTO_INCREMENT,
  DESCRICAO VARCHAR(50) NULL,
  UF VARCHAR(2) NULL,
  PRIMARY KEY(ID_ESTADO)
);

CREATE TABLE CIDADE (
  ID_CIDADE INT NOT NULL AUTO_INCREMENT,
  ID_ESTADO INT NOT NULL,
  DESCRICAO VARCHAR(50) NULL,
  PRIMARY KEY(ID_CIDADE)
);

ALTER TABLE CIDADE ADD CONSTRAINT `fk_estado` FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO) ;

CREATE TABLE BAIRRO (
  ID_BAIRRO INT NOT NULL AUTO_INCREMENT,
  ID_CIDADE INT NOT NULL,
  DESCRICAO VARCHAR(50) NULL,
  PRIMARY KEY(ID_BAIRRO)
);

ALTER TABLE BAIRRO ADD CONSTRAINT `fk_cidade` FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID_CIDADE) ;

CREATE TABLE CATEGORIA (
  ID_CATEGORIA INT NOT NULL AUTO_INCREMENT,
  DESCRICAO VARCHAR(50) NULL,
  PRIMARY KEY(ID_CATEGORIA)
);

CREATE TABLE TEMPO (
  ID_TEMPO INT NOT NULL AUTO_INCREMENT,
  ANO_CONSTRUCAO INT NULL,
  PRIMARY KEY(ID_TEMPO)
);

CREATE TABLE PROPRIETARIO (
  ID_PROPRIETARIO INT NOT NULL AUTO_INCREMENT,
  FAIXA_SALARIO INT NULL,
  FILHOS INT NULL,
  SEXO INT NULL,
  CLASSE_SOCIAL INT NULL,
  PROFISSAO VARCHAR(50) NULL,
  DEFICIENTE VARCHAR(50) NULL,
  PRIMARY KEY(ID_PROPRIETARIO)
);

ALTER TABLE PROPRIETARIO ADD CONSTRAINT `fk_bairro` FOREIGN KEY (ID_BAIRRO) REFERENCES BAIRRO(ID_BAIRRO) ;

CREATE TABLE FATO_IMOVEL (
  ID_FATO_IMOVEL INT NOT NULL AUTO_INCREMENT,
  ID_PROPRIETARIO INT NULL,
  ID_BAIRRO INT NULL,
  ID_TEMPO INT NULL,
  ID_CATEGORIA INT NULL,
  SITUACAO INT NULL,
  FAIXA_AREA_TOTAL INT NULL,
  AREA_PRIVATIVA INT NULL,
  FAIXA_IPTU INT NULL,
  CONDOMINIO INT NULL,
  PLANTA INT NULL,
  SACADA INT NULL,
  PORTARIA INT NULL,
  ELEVADOR INT NULL,
  CHURRASQUEIRA INT NULL,
  DORMITORIOS INT NULL,
  SUITES INT NULL,
  VAGAS_ESTACIONAMENTO INT NULL,
  BANHEIROS INT NULL,
  COMPLEMENTO VARCHAR(100) NULL,
  FAIXA_VALOR_VENDA INT NULL,
  FAIXA_VALOR_ALUGUEL INT NULL,
  PRIMARY KEY(ID_FATO_IMOVEL)
);

ALTER TABLE FATO_IMOVEL ADD CONSTRAINT `fk_fato_proprietario` FOREIGN KEY (ID_PROPRIETARIO) REFERENCES PROPRIETARIO(ID_PROPRIETARIO) ;
ALTER TABLE FATO_IMOVEL ADD CONSTRAINT `fk_fato_bairro` FOREIGN KEY (ID_BAIRRO) REFERENCES BAIRRO(ID_BAIRRO) ;
ALTER TABLE FATO_IMOVEL ADD CONSTRAINT `fk_fato_tempo` FOREIGN KEY (ID_TEMPO) REFERENCES TEMPO(ID_TEMPO) ;
ALTER TABLE FATO_IMOVEL ADD CONSTRAINT `fk_fato_categoria` FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA) ;

commit;


